version: "3.9"
services:
  app:
    build: ./infra/app
    volumes:
      - ./iterator:/data

  web:
    build: ./infra/web
    ports:
      - 8080:80
    volumes:
      - ./iterator:/data
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/db
    ports:
      - 33066:3306
    volumes:
      - php_sandbox-store:/var/lib/mysql

volumes:
  php_sandbox-store: